services:
  - type: web
    name: IB-HEX-BOT
    env: node
    plan: free
    buildCommand: yarn install --ignore-engines || npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: "20"
